
export enum PostType {
  TEXT = 'TEXT',
  CODE_SNIPPET = 'CODE_SNIPPET',
  TUTORIAL = 'TUTORIAL',
  QUESTION = 'QUESTION',
  SHOWCASE = 'SHOWCASE',
  DISCUSSION = 'DISCUSSION',
  RESOURCE_SHARE = 'RESOURCE_SHARE',
}

export enum DifficultyLevel {
  BEGINNER = 'BEGINNER',
  INTERMEDIATE = 'INTERMEDIATE',
  ADVANCED = 'ADVANCED',
  EXPERT = 'EXPERT',
}